version: '3.7'

services:

  movie_api:
    container_name: movie_api
    build:
      context: .
    restart: always
    networks:
      - movie_net
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/

networks:
  movie_net:
    name: movie_net
    driver: bridge