version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es
    environment:
      - discovery.type=single-node
    restart: always
    ports:
      - 9200:9200
    networks:
      - movie_net
    volumes:
      - es_data:/data

  redis:
    image: redis:alpine
    volumes:
      - ./state/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - movie_net
    depends_on:
      - elasticsearch

  db:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    restart: always
    networks:
      - movie_net
    ports:
      - 5432:5432
    volumes:
      - db-data-4:/var/lib/postgresql/data
      - ../Admin_panel_sprint_2/movies_admin/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  admin_panel:
    image: ${DOCKER_REGISTRY-}admin_panel
    container_name: admin_panel
    build:
      context: ../Admin_panel_sprint_2/movies_admin/
    env_file:
      - .env
    restart: always
    networks:
      - movie_net
    volumes:
      - ../Admin_panel_sprint_2/movies_admin/:/usr/src/app/
    depends_on:
      - db

  nginx:
    container_name: nginx
    image: nginx:1.19.2
    restart: always
    networks:
      - movie_net
    depends_on:
      - db
      - admin_panel
    ports:
      - 80:80
    volumes:
      - ../Admin_panel_sprint_2/movies_admin/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../Admin_panel_sprint_2/movies_admin/docker/nginx/configs:/etc/nginx/conf.d:ro
      - ../Admin_panel_sprint_2/movies_admin/static/:/static

  movie_etl:
    image: ${DOCKER_REGISTRY-}movie_etl
    container_name: movie_etl
    build:
      context: ../ETL/postgres_to_es/
    env_file:
      - .env
    restart: always
    networks:
      - movie_net
    volumes:
      - ../ETL/postgres_to_es/:/usr/src/postgres_to_es/
    depends_on:
      - redis
      - elasticsearch
      - db
    entrypoint: [ "./wait-for-it.sh", "-s" ,"-t", "20", "elasticsearch:9200", "--" ]
    command: [ "echo", "You Know, for Search" ]


  movie_api:
    image: ${DOCKER_REGISTRY-}movies_api
    container_name: movie_api
    build:
      context: .
    restart: always
    networks:
      - movie_net
    ports:
      - 8000:8000
    depends_on:
      - redis
      - elasticsearch
      - db
    entrypoint: [ "./wait-for-it.sh", "-s" ,"-t", "20", "elasticsearch:9200", "--" ]
    command: ["echo", "You Know, for Search"]
    volumes:
      - ./:/usr/src/app/


volumes:
  es_data:
  redis_data:
  db-data-4:

networks:
  movie_net:
    name: movie_net
    driver: bridge

