version: '3.7'

services:

  movies_app:
    container_name: movies_app
    build:
      context: .
    restart: always
    networks:
      - movie_net
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/

networks:
  movie_net:
    name: custom_network
    driver: bridge