version: '3.5'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: es
    environment:
      - discovery.type=single-node
    restart: always
    networks:
      - movie_net
    volumes:
      - es_data:/usr/share/elasticsearch/data

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - movie_net
    depends_on:
      - elasticsearch

  db:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    restart: always
    networks:
      - movie_net
    volumes:
      - db-data-4:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  admin_panel:
    image: "ghcr.io/s-klimov/admin_panel_sprint_2:main"
    container_name: admin_panel
    env_file:
      - .env
    restart: always
    networks:
      - movie_net
    volumes:
      - ./config.json:/usr/src/app/config.json
      - django-static:/usr/src/app/static
    depends_on:
      - db

  nginx:
    image: nginx:1.19.2
    container_name: nginx
    restart: always
    networks:
      - movie_net
    depends_on:
      - db
      - admin_panel
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/configs:/etc/nginx/conf.d:ro
      - django-static:/static

  movie_etl:
    image: "ghcr.io/s-klimov/etl:main"
    container_name: movie_etl
    env_file:
      - .env
    networks:
      - movie_net
    restart: always
    volumes:
      - ./config.json:/usr/src/postgres_to_es/config.json
    depends_on:
      - redis
      - elasticsearch
      - db

  movie_api:
    <<: &movie_api
      container_name: movie_api
      build:
        context: .
        args:
          ENV: development
      restart: always
      networks:
        - movie_net
      depends_on:
        - redis
        - elasticsearch
        - db


volumes:
  es_data:
  redis_data:
  db-data-4:
  django-static:

networks:
  movie_net:
    name: movie_net
